services:
  - docker

script:
  - docker build -t "$DOCKER_USERNAME"/node-awscli:8.0 .

deploy:
  provider: script
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push "$DOCKER_USERNAME"/node-awscli:8.0
  on:
    branch: master
