services:
  - docker

before_script: export VERSION=8.16
script: docker build -t "$DOCKER_USERNAME"/node-awscli:$VERSION .

deploy:
  skip-cleanup: true
  provider: script
  script: bash docker_push
  on:
    branch: master
